title: Joarder's Summer
author: Joarder Rashid
email: mahinslays@gmail.com
description: Joarder's Summer had many fun expereineces he would love to share :)

# social links
twitter_username: JoarderRashid
github_username: joarder162 

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
